<script setup lang="ts">
import { computed, ref } from 'vue'
import { analyze, bitBytes, bom, byteCount, cpLabel, graphemes, hexBytes, normalizeNewlines, type EncodingName } from './encoding'
const text=ref('Hello 😀 世界\nSelect some text to inspect it.'); const inputOpen=ref(true); const active=ref('Bytes'); const findOpen=ref(false); const query=ref(''); const caseSensitive=ref(false); const wholeWord=ref(false); const matchIndex=ref(0); const inputEl=ref<HTMLTextAreaElement|null>(null); const includeBom=ref(false); const alloc=ref(4096); const sel=ref({start:0,end:0}); const pinned=ref('😀'); const hovered=ref('')
const fileEncoding=ref<EncodingName>('UTF-8'); const newlineStyle=ref<'Preserve'|'LF'|'CRLF'|'CR'>('Preserve')
const selected=computed(()=>text.value.slice(sel.value.start,sel.value.end)); const total=computed(()=>analyze(text.value)); const ss=computed(()=>analyze(selected.value));
const selectionPercent=computed(()=>total.value.sizes['UTF-8'].bytes.length ? ss.value.sizes['UTF-8'].bytes.length/total.value.sizes['UTF-8'].bytes.length*100 : 0)
const matches=computed(()=>{if(!query.value)return [] as {start:number,end:number}[]; const hay=caseSensitive.value?text.value:text.value.toLocaleLowerCase(); const needle=caseSensitive.value?query.value:query.value.toLocaleLowerCase(); const out:{start:number,end:number}[]=[]; let from=0; while(needle && (from=hay.indexOf(needle,from))!==-1){const before=from===0?' ':hay[from-1], after=from+needle.length>=hay.length?' ':hay[from+needle.length]; const ok=!wholeWord.value || (!/[\\p{L}\\p{N}_]/u.test(before) && !/[\\p{L}\\p{N}_]/u.test(after)); if(ok)out.push({start:from,end:from+needle.length}); from+=Math.max(needle.length,1)} return out})
function gotoMatch(delta=0){if(!matches.value.length)return; matchIndex.value=(matchIndex.value+delta+matches.value.length)%matches.value.length; const m=matches.value[matchIndex.value]; requestAnimationFrame(()=>{inputEl.value?.focus(); inputEl.value?.setSelectionRange(m.start,m.end); sel.value=m})}
const size=(s:string,e:EncodingName)=>byteCount(s,e); const hex=(s:string,e:EncodingName='UTF-8')=>hexBytes(s,e); const bin=(s:string,e:EncodingName='UTF-8')=>bitBytes(s,e)
const fileText=computed(()=>normalizeNewlines(text.value,newlineStyle.value)); const payload=computed(()=>size(fileText.value,fileEncoding.value)); const bomSize=computed(()=>includeBom.value?bom(fileEncoding.value).length:0); const modeled=computed(()=>payload.value+bomSize.value); const allocation=computed(()=>modeled.value?Math.ceil(modeled.value/alloc.value)*alloc.value:0)
function selection(e:Event){const t=e.target as HTMLTextAreaElement; sel.value={start:t.selectionStart,end:t.selectionEnd}; if(t.selectionStart!==t.selectionEnd) active.value='Highlight'}
function csvCell(v:string){return `"${v.replaceAll('"','""')}"`}
function save(kind:'md'|'csv'){const a=total.value; const u8=a.sizes['UTF-8'].bytes.length; let body=''; if(kind==='md') body=`# Byte & Bit Reader Report\n\n## Message Summary\n\n- Graphemes: ${a.graphemes}\n- Code points: ${a.codepoints}\n- UTF-16 code units: ${a.utf16Units}\n- UTF-8: ${u8} bytes / ${u8*8} bits\n- UTF-16: ${a.sizes['UTF-16 LE'].bytes.length} bytes / ${a.sizes['UTF-16 LE'].bytes.length*8} bits\n- UTF-32: ${a.sizes['UTF-32 LE'].bytes.length} bytes / ${a.sizes['UTF-32 LE'].bytes.length*8} bits\n\n## File / BOM Analysis\n\n- Encoding: ${fileEncoding.value}\n- Newlines: ${newlineStyle.value}\n- Payload: ${payload.value} bytes\n- BOM: ${bomSize.value} bytes\n- Modeled file size: ${modeled.value} bytes\n\n## Original Message\n\n${text.value}\n`; else body=`section,item,value,bytes,bits\nsummary,UTF-8,,${u8},${u8*8}\nsummary,UTF-16 LE,,${a.sizes['UTF-16 LE'].bytes.length},${a.sizes['UTF-16 LE'].bytes.length*8}\nsummary,UTF-32 LE,,${a.sizes['UTF-32 LE'].bytes.length},${a.sizes['UTF-32 LE'].bytes.length*8}\nfile,${fileEncoding.value},payload,${payload.value},${payload.value*8}\nfile,BOM,,${bomSize.value},${bomSize.value*8}\nsource,original_message,${csvCell(text.value)},,\n`; const link=document.createElement('a'); link.href=URL.createObjectURL(new Blob([body],{type:kind==='csv'?'text/csv':'text/markdown'})); link.download=`byte-bit-report.${kind}`; link.click(); URL.revokeObjectURL(link.href)}
const tabs=['Bytes','Highlight','Character','File / BOM','Bits']; const encodings:EncodingName[]=['UTF-8','UTF-16 LE','UTF-16 BE','UTF-32 LE','UTF-32 BE','ASCII','Latin-1']
</script>
<template>
<div class="page"><main class="app-card">
<header><div class="brand"><span class="logo">01</span><div><b>BYTE & BIT READER</b><small>Unicode & storage inspector</small></div></div><nav><button @click="findOpen=!findOpen" title="Find">⌕ <span>Find</span></button><button @click="save('csv')" title="Export CSV">⇩ <span>CSV</span></button><button @click="save('md')" title="Export Markdown">⇩ <span>MD</span></button><button title="Settings">⚙</button></nav></header>
<div v-if="findOpen" class="findbar"><b>Find</b><input v-model="query" @input="matchIndex=0" @keydown.enter.prevent="gotoMatch($event.shiftKey?-1:1)" placeholder="Find text…"><span>{{matches.length ? matchIndex+1 : 0}} / {{matches.length}}</span><button @click="gotoMatch(-1)" title="Previous">‹</button><button @click="gotoMatch(1)" title="Next">›</button><label><input type="checkbox" v-model="caseSensitive"> Aa</label><label><input type="checkbox" v-model="wholeWord"> Whole</label><button @click="findOpen=false">×</button></div>
<section class="input-card"><div class="section-head" @click="inputOpen=!inputOpen"><div><b>{{inputOpen?'▾':'▸'}} INPUT</b><span>Paste or type any text</span></div><div class="summary"><b>{{total.sizes['UTF-8'].bytes.length}} B</b><span>{{total.sizes['UTF-8'].bytes.length*8}} bits</span></div></div><div v-show="inputOpen" class="input-wrap"><textarea ref="inputEl" v-model="text" @select="selection" @keyup="selection" @mouseup="selection" spellcheck="false"></textarea><div class="status"><span>{{total.graphemes}} graphemes</span><span>{{total.codepoints}} code points</span><span>{{total.utf16Units}} UTF-16 units</span><span>UTF-8 {{total.sizes['UTF-8'].bytes.length}} B</span></div></div></section>
<section class="workspace"><div class="tabs"><button v-for="t in tabs" :class="{active:active===t}" @click="active=t">{{t}}</button></div>
<div class="panel" v-if="active==='Bytes'"><div class="hero-grid"><article><small>MESSAGE SIZE · UTF-8</small><strong>{{total.sizes['UTF-8'].bytes.length}} bytes</strong><b>{{total.sizes['UTF-8'].bytes.length*8}} bits</b></article><article><small>LARGEST UTF-8 CHARACTER</small><strong class="char">{{total.largest}}</strong><b>{{size(total.largest,'UTF-8')}} bytes · {{size(total.largest,'UTF-8')*8}} bits</b></article></div><h3>Encoding comparison</h3><div class="rows"><div v-for="e in encodings"><b>{{e}}</b><span v-if="total.sizes[e].valid">{{total.sizes[e].bytes.length}} bytes</span><span v-else>Not representable ({{total.sizes[e].unrepresentable}})</span><span v-if="total.sizes[e].valid">{{total.sizes[e].bytes.length*8}} bits</span></div></div></div>
<div class="panel" v-else-if="active==='Highlight'"><div v-if="selected" class="selection"><small>HIGHLIGHTED SELECTION</small><blockquote>{{selected}}</blockquote><div class="metrics"><span><b>{{ss.graphemes}}</b> graphemes</span><span><b>{{ss.codepoints}}</b> code points</span><span><b>{{ss.sizes['UTF-8'].bytes.length}} B</b> UTF-8</span><span><b>{{ss.sizes['UTF-8'].bytes.length*8}}</b> bits</span></div><div class="rows"><div><b>UTF-8</b><span>{{ss.sizes['UTF-8'].bytes.length}} bytes</span><span>{{ss.sizes['UTF-8'].bytes.length*8}} bits</span></div><div><b>UTF-16</b><span>{{ss.sizes['UTF-16 LE'].bytes.length}} bytes</span><span>{{ss.sizes['UTF-16 LE'].bytes.length*8}} bits</span></div><div><b>UTF-32</b><span>{{ss.sizes['UTF-32 LE'].bytes.length}} bytes</span><span>{{ss.sizes['UTF-32 LE'].bytes.length*8}} bits</span></div></div></div><div v-else class="empty">Highlight text in the input box to analyze only that selection.</div></div>
<div class="panel" v-else-if="active==='Character'"><p class="hint">Hover for a quick look. Click a character to pin it here.</p><div class="charstrip"><button v-for="(c,i) in graphemes(text)" :key="i" @click="pinned=c" :title="`${size(c,'UTF-8')} bytes · ${size(c,'UTF-8')*8} bits`">{{c===' '?'␠':c==='\n'?'↵':c}}</button></div><div class="character-detail"><strong>{{pinned}}</strong><div><small>CODE POINT</small><b>{{cpLabel(pinned)}}</b></div><div><small>UTF-8</small><b>{{size(pinned,'UTF-8')}} bytes · {{size(pinned,'UTF-8')*8}} bits</b></div><div class="wide"><small>HEX</small><code>{{hex(pinned)}}</code><small>BINARY</small><code>{{bin(pinned)}}</code></div></div></div>
<div class="panel" v-else-if="active==='File / BOM'">
<div class="control"><div><b>File encoding</b><small>Model the encoded payload independently from the Bytes tab.</small></div><select v-model="fileEncoding"><option v-for="e in encodings" :value="e">{{e}}</option></select></div>
<div class="control"><div><b>Line endings</b><small>Preserve input or model LF, CRLF, or CR without double-counting.</small></div><select v-model="newlineStyle"><option>Preserve</option><option>LF</option><option>CRLF</option><option>CR</option></select></div>
<div class="control"><div><b>Include BOM</b><small>{{bom(fileEncoding).length ? `${bom(fileEncoding).length} byte BOM available for ${fileEncoding}.` : 'No BOM is defined here for this encoding.'}}</small></div><input type="checkbox" v-model="includeBom" :disabled="!bom(fileEncoding).length"></div>
<div class="control"><div><b>Filesystem allocation unit</b><small>Optional estimate for space consumed on disk.</small></div><select v-model="alloc"><option :value="512">512 B</option><option :value="4096">4 KiB</option><option :value="8192">8 KiB</option></select></div>
<div class="rows"><div><b>Text payload</b><span>{{payload}} bytes</span></div><div><b>BOM overhead</b><span>{{bomSize}} bytes</span></div><div class="total"><b>Modeled file size</b><span>{{modeled}} bytes</span></div><div><b>Estimated allocation</b><span>{{allocation}} bytes</span></div></div></div>
<div class="panel" v-else><h3>UTF-8 bit stream</h3><code class="bitbox">{{bin(text)}}</code></div>
</section></main></div>
</template>
