import { describe,expect,it } from 'vitest'
import { compareRtf,inspectRtf,parseColorTable,parseFontTable,parseRtfRuns } from './rtf'
describe('RTF comparison',()=>{
 it('separates raw growth from visible text growth',()=>{const a='{\\rtf1 Hello}',b='{\\rtf1\\b Hello world\\b0}'; const d=compareRtf(inspectRtf(a,a.length),inspectRtf(b,b.length)); expect(d.rawByteDelta).toBeGreaterThan(d.visibleUtf8Delta); expect(d.controlWordDelta).toBeGreaterThan(0); expect(d.formattingChanges.some(x=>x.includes('Bold'))).toBe(true); expect(d.lessons.length).toBeGreaterThan(0) it('classifies common formatting controls',()=>{const a='{\\rtf1 plain}',b='{\\rtf1\\b bold\\b0 \\i italic\\i0 \\ul under\\ul0 \\fs28 size \\cf1 red \\qc centered\\par}'; const s=inspectRtf(b,b.length); expect(s.formatting.bold).toBeGreaterThan(0); expect(s.formatting.italic).toBeGreaterThan(0); expect(s.formatting.underline).toBeGreaterThan(0); expect(s.formatting.fontSize).toBe(1); expect(s.formatting.foregroundColor).toBe(1); expect(s.formatting.alignCenter).toBe(1); expect(compareRtf(inspectRtf(a,a.length),s).formattingChanges.length).toBeGreaterThan(4)})
})
 it('tracks escape representation changes',()=>{const a='{\\rtf1 A}',b="{\\rtf1 \\'e9}"; const d=compareRtf(inspectRtf(a,a.length),inspectRtf(b,b.length)); expect(d.hexEscapeDelta).toBe(1)})
 it('does not call every byte difference formatting',()=>{const a='{\\rtf1 cat}',b='{\\rtf1 dog}'; const d=compareRtf(inspectRtf(a,a.length),inspectRtf(b,b.length)); expect(d.controlWordDelta).toBe(0)})
 it('tracks formatting state by text run and restores group state',()=>{const runs=parseRtfRuns('{\\rtf1 plain {\\b bold {\\i both} bold2} plain2}'); const bold=runs.find(r=>r.text.includes('bold ')); const both=runs.find(r=>r.text.includes('both')); const plain2=runs.find(r=>r.text.includes('plain2')); expect(bold?.style.bold).toBe(true); expect(both?.style.bold).toBe(true); expect(both?.style.italic).toBe(true); expect(plain2?.style.bold).toBe(false); expect(plain2?.style.italic).toBe(false)})
 it('tracks size, color, and paragraph alignment state',()=>{const runs=parseRtfRuns('{\\rtf1\\fs28\\cf2\\qc Centered\\par\\pard Left}'); const centered=runs.find(r=>r.text.includes('Centered')); const left=runs.find(r=>r.text.includes('Left')); expect(centered?.style.fontSizeHalfPoints).toBe(28); expect(centered?.style.foregroundColor).toBe(2); expect(centered?.style.alignment).toBe('center'); expect(left?.style.alignment).toBe('left')})
 it('resolves font table indexes to names',()=>{const fonts=parseFontTable('{\\rtf1{\\fonttbl{\\f0\\fswiss Arial;}{\\f2\\froman Times New Roman;}}\\f2 Hi}'); expect(fonts.find(f=>f.index===0)?.name).toBe('Arial'); expect(fonts.find(f=>f.index===2)?.name).toBe('Times New Roman'); expect(fonts.find(f=>f.index===2)?.family).toBe('roman')})
 it('resolves color table indexes to RGB',()=>{const colors=parseColorTable('{\\rtf1{\\colortbl;\\red255\\green0\\blue0;\\red10\\green20\\blue30;}x}'); expect(colors.find(c=>c.index===1)).toMatchObject({red:255,green:0,blue:0}); expect(colors.find(c=>c.index===2)).toMatchObject({red:10,green:20,blue:30})})
 it('includes resolved tables in document inspection',()=>{const raw='{\\rtf1{\\fonttbl{\\f0\\fswiss Arial;}}{\\colortbl;\\red255\\green0\\blue0;}\\f0\\cf1\\fs28 Red}'; const s=inspectRtf(raw,raw.length); expect(s.fonts[0].name).toBe('Arial'); expect(s.colors[0].index).toBe(1); expect(s.runs.some(r=>r.text.includes('Red')&&r.style.font===0&&r.style.foregroundColor===1&&r.style.fontSizeHalfPoints===28)).toBe(true)})
 it('maps rendered runs to RTF source controls',()=>{const raw='{\\rtf1 plain {\\b\\fs28 bold} end}';const runs=parseRtfRuns(raw);const bold=runs.find(r=>r.text.includes('bold'));expect(bold?.style.bold).toBe(true);expect(bold?.style.fontSizeHalfPoints).toBe(28);expect(bold?.controls.some(c=>c.word==='b'&&c.explanation.includes('Bold'))).toBe(true);expect(bold?.controls.some(c=>c.word==='fs'&&c.parameter===28)).toBe(true);expect(bold!.sourceStart).toBeLessThan(bold!.sourceEnd)})
 it('keeps source spans distinct across adjacent formatted runs',()=>{const raw='{\\rtf1 A {\\b B} C}';const runs=parseRtfRuns(raw);const a=runs.find(r=>r.text.includes('A '))!,b=runs.find(r=>r.text.includes('B'))!,cc=runs.find(r=>r.text.includes(' C'))!;expect(a.sourceEnd).toBeLessThanOrEqual(b.sourceStart);expect(b.sourceEnd).toBeLessThanOrEqual(cc.sourceStart);expect(raw.slice(b.sourceStart,b.sourceEnd)).toContain('B');expect(b.controls.some(x=>raw.slice(x.sourceStart,x.sourceEnd).includes('\\b'))).toBe(true)})
})
