import {describe,expect,it} from 'vitest'
import {buildRtfModel} from './rtfModel'
describe('RTF semantic model',()=>{
 it('computes inherited formatting and restores group state',()=>{const m=buildRtfModel('{\\rtf1 plain {\\b\\fs28 bold {\\i both} bold2} plain2}');const bold=m.runs.find(r=>r.text.includes('bold '))!,both=m.runs.find(r=>r.text.includes('both'))!,plain=m.runs.find(r=>r.text.includes('plain2'))!;expect(bold.style).toMatchObject({bold:true,fontSizeHalfPoints:28});expect(both.style).toMatchObject({bold:true,italic:true});expect(plain.style.bold).toBe(false)})
 it('creates paragraphs and preserves source token links',()=>{const s='{\\rtf1\\qc One\\par\\pard Two}';const m=buildRtfModel(s);expect(m.paragraphs.length).toBe(2);expect(m.paragraphs[0].alignment).toBe('center');expect(m.paragraphs[1].alignment).toBe('left');const one=m.runs.find(r=>r.text.includes('One'))!;expect(one.sourceTokens.length).toBeGreaterThan(0);expect(s.slice(one.sourceStart,one.sourceEnd)).toContain('One')})
 it('exposes destinations instead of rendering their contents',()=>{const m=buildRtfModel('{\\rtf1{\\fonttbl{\\f0\\fswiss Arial;}}{\\*\\generator Test;}\\f0 Hello}');expect(m.destinations.some(d=>d.name==='fonttbl')).toBe(true);expect(m.destinations.some(d=>d.name==='generator'&&d.ignorable)).toBe(true);expect(m.runs.map(r=>r.text).join('')).toContain('Hello');expect(m.runs.map(r=>r.text).join('')).not.toContain('Arial')})
 it('resolves model font and color tables',()=>{const m=buildRtfModel('{\\rtf1{\\fonttbl{\\f0\\fswiss Arial;}}{\\colortbl;\\red255\\green0\\blue0;}\\f0\\cf1 Red}');expect(m.fonts).toContainEqual({index:0,name:'Arial'});expect(m.colors).toContainEqual({index:1,red:255,green:0,blue:0});expect(m.runs.find(r=>r.text.includes('Red'))?.style).toMatchObject({font:0,foregroundColor:1})})
 it('records exact control origins and inherits them into nested runs',()=>{const s='{\\rtf1\\f2\\fs28\\b outer {\\i inner}}';const m=buildRtfModel(s),inner=m.runs.find(r=>r.text.includes('inner'))!;expect(inner.origins.bold?.control).toBe('\\b');expect(inner.origins.font?.value).toBe(2);expect(inner.origins.fontSizeHalfPoints?.value).toBe(28);expect(inner.origins.italic?.control).toBe('\\i');expect(s.slice(inner.origins.bold!.sourceStart,inner.origins.bold!.sourceEnd)).toBe('\\b')})
 it('restores provenance when leaving a nested override',()=>{const m=buildRtfModel('{\\rtf1\\b before {\\b0 off} after}'),before=m.runs.find(r=>r.text.includes('before'))!,off=m.runs.find(r=>r.text.includes('off'))!,after=m.runs.find(r=>r.text.includes('after'))!;expect(before.origins.bold?.value).toBe(true);expect(off.origins.bold?.value).toBe(false);expect(after.origins.bold?.value).toBe(true);expect(after.origins.bold?.sourceStart).toBe(before.origins.bold?.sourceStart)})
 it('marks plain and pard as reset provenance',()=>{const m=buildRtfModel('{\\rtf1\\b\\qc A\\plain B\\pard C}'),b=m.runs.find(r=>r.text.includes('B'))!,cc=m.runs.find(r=>r.text.includes('C'))!;expect(b.origins.bold).toMatchObject({value:false,control:'\\plain',kind:'reset'});expect(cc.origins.alignment).toMatchObject({value:'left',control:'\\pard',kind:'reset'})})
 it('keeps an override history with previous and new values',()=>{const m=buildRtfModel('{\\rtf1\\b before \\b0 off}'),off=m.runs.find(r=>r.text.includes('off'))!,h=off.history.bold!;expect(h.map(x=>x.kind)).toEqual(['applied','override']);expect(h[0]).toMatchObject({previousValue:false,value:true,control:'\\b'});expect(h[1]).toMatchObject({previousValue:true,value:false,control:'\\b0'})})
 it('scopes nested override history without leaking it to siblings',()=>{const m=buildRtfModel('{\\rtf1\\b before {\\b0 off} after}'),off=m.runs.find(r=>r.text.includes('off'))!,after=m.runs.find(r=>r.text.includes('after'))!;expect(off.history.bold?.length).toBe(2);expect(after.history.bold?.length).toBe(1);expect(after.origins.bold?.value).toBe(true)})
 it('records the group scope for provenance events',()=>{const s='{\\rtf1 {\\i inner}}',m=buildRtfModel(s),inner=m.runs.find(r=>r.text.includes('inner'))!,e=inner.history.italic![0];expect(e.groupStart).toBe(s.indexOf('{',1));expect(e.groupEnd).toBe(s.lastIndexOf('}') )})
})
