import {parseRtfTree,type RtfNode,type RtfDiagnostic} from './rtfParser'
import type {RtfToken} from './rtfLexer'
export type RtfModelFont={index:number;name:string;sourceStart:number;sourceEnd:number}
export type RtfModelColor={index:number;red:number;green:number;blue:number;sourceStart:number;sourceEnd:number}
export type RtfStyleProperty=keyof RtfComputedStyle
export type RtfProvenanceKind='applied'|'reset'|'override'|'restored'
export type RtfPropertyOrigin={property:RtfStyleProperty;value:RtfComputedStyle[RtfStyleProperty];control:string;sourceStart:number;sourceEnd:number;kind:'applied'|'reset'}
export type RtfReferenceTarget={kind:'font'|'color';index:number;label:string;sourceStart:number;sourceEnd:number}
export type RtfProvenanceEvent={property:RtfStyleProperty;value:RtfComputedStyle[RtfStyleProperty];previousValue:RtfComputedStyle[RtfStyleProperty];control:string;sourceStart:number;sourceEnd:number;kind:RtfProvenanceKind;groupStart:number;groupEnd:number|null;reference?:RtfReferenceTarget}
export type RtfComputedStyle={bold:boolean;italic:boolean;underline:boolean;font:number|null;fontSizeHalfPoints:number|null;foregroundColor:number|null;backgroundColor:number|null;alignment:'left'|'center'|'right'|'justify';leftIndentTwips:number;rightIndentTwips:number;firstLineIndentTwips:number;spaceBeforeTwips:number;spaceAfterTwips:number;lineSpacingTwips:number|null;tabStopsTwips:number[]}
export type RtfModelRun={text:string;start:number;end:number;sourceStart:number;sourceEnd:number;style:RtfComputedStyle;origins:Partial<Record<RtfStyleProperty,RtfPropertyOrigin>>;history:Partial<Record<RtfStyleProperty,RtfProvenanceEvent[]>>;sourceTokens:RtfToken[]}
export type RtfParagraph={index:number;start:number;end:number;sourceStart:number;sourceEnd:number;runs:RtfModelRun[];alignment:RtfComputedStyle['alignment']}
export type RtfDestination={name:string;sourceStart:number;sourceEnd:number;ignorable:boolean}
export type RtfModel={source:string;paragraphs:RtfParagraph[];runs:RtfModelRun[];destinations:RtfDestination[];fonts:RtfModelFont[];colors:RtfModelColor[];diagnostics:RtfDiagnostic[]}
type State={style:RtfComputedStyle;origins:Partial<Record<RtfStyleProperty,RtfPropertyOrigin>>;history:Partial<Record<RtfStyleProperty,RtfProvenanceEvent[]>>;groupStart:number;groupEnd:number|null;skip:boolean;destination:string|null;uc:number}
const base=():RtfComputedStyle=>({bold:false,italic:false,underline:false,font:null,fontSizeHalfPoints:null,foregroundColor:null,backgroundColor:null,alignment:'left',leftIndentTwips:0,rightIndentTwips:0,firstLineIndentTwips:0,spaceBeforeTwips:0,spaceAfterTwips:0,lineSpacingTwips:null,tabStopsTwips:[]})
const destinationWords=new Set(['fonttbl','colortbl','stylesheet','info','pict','object','header','footer','headerl','headerr','footerl','footerr','listtable','listoverridetable','generator'])
const cloneStyle=(s:RtfComputedStyle):RtfComputedStyle=>({...s,tabStopsTwips:[...s.tabStopsTwips]})
const same=(a:RtfComputedStyle,b:RtfComputedStyle)=>JSON.stringify(a)===JSON.stringify(b)
const sameOrigins=(a:State['origins'],b:State['origins'])=>JSON.stringify(a)===JSON.stringify(b)
const origin=(state:State,property:RtfStyleProperty,value:RtfComputedStyle[RtfStyleProperty],t:RtfToken,kind:RtfPropertyOrigin['kind']='applied')=>{const previous=state.origins[property],previousValue=(previous?.value??base()[property]) as RtfComputedStyle[RtfStyleProperty];const eventKind:RtfProvenanceKind=kind==='reset'?'reset':previous?'override':'applied';state.origins[property]={property,value,control:t.raw.trim(),sourceStart:t.start,sourceEnd:t.end,kind};state.history[property]=[...(state.history[property]||[]),{property,value,previousValue,control:t.raw.trim(),sourceStart:t.start,sourceEnd:t.end,kind:eventKind,groupStart:state.groupStart,groupEnd:state.groupEnd}]}
export function buildRtfModel(source:string):RtfModel{
 const tree=parseRtfTree(source),runs:RtfModelRun[]=[],destinations:RtfDestination[]=[];let textPos=0
 const emit=(text:string,tokens:RtfToken[],style:RtfComputedStyle,origins:State['origins'],history:State['history'])=>{if(!text)return;const ss=tokens[0]?.start??0,se=tokens.at(-1)?.end??ss,last=runs.at(-1);if(last&&same(last.style,style)&&sameOrigins(last.origins,origins)&&last.end===textPos&&last.sourceEnd===ss){last.text+=text;last.end+=text.length;last.sourceEnd=se;last.sourceTokens.push(...tokens)}else runs.push({text,start:textPos,end:textPos+text.length,sourceStart:ss,sourceEnd:se,style:cloneStyle(style),origins:{...origins},history:Object.fromEntries(Object.entries(history).map(([k,v])=>[k,[...(v||[])]])),sourceTokens:[...tokens]});textPos+=text.length}
 const walk=(nodes:RtfNode[],incoming:State)=>{const state:State={style:cloneStyle(incoming.style),origins:{...incoming.origins},history:Object.fromEntries(Object.entries(incoming.history).map(([k,v])=>[k,[...(v||[])]])),groupStart:incoming.groupStart,groupEnd:incoming.groupEnd,skip:incoming.skip,destination:incoming.destination,uc:incoming.uc};let star=false
  for(const node of nodes){
   if(node.type==='group'){const before=destinations.length;const child:State={...state,style:cloneStyle(state.style),origins:{...state.origins},history:Object.fromEntries(Object.entries(state.history).map(([k,v])=>[k,[...(v||[])]])),groupStart:node.start,groupEnd:node.end};walk(node.children,child);if(!node.unclosed&&node.close)for(const property of Object.keys(state.style) as RtfStyleProperty[]){if(child.style[property]!==state.style[property])state.history[property]=[...(state.history[property]||[]),{property,value:state.style[property],previousValue:child.style[property],control:node.close.raw,sourceStart:node.close.start,sourceEnd:node.close.end,kind:'restored',groupStart:node.start,groupEnd:node.end}]}for(let di=before;di<destinations.length;di++)if(destinations[di].sourceEnd===destinations[di].sourceStart||destinations[di].sourceEnd===node.children[0]?.end)destinations[di].sourceEnd=node.end;continue}
   const t=node.token
   if(t.type==='control-symbol'){if(t.symbol==='*'){star=true;continue}if(!state.skip&&['\\','{','}'].includes(t.symbol||''))emit(t.symbol!,[t],state.style,state.origins,state.history);else if(!state.skip&&t.symbol==='~')emit('\u00a0',[t],state.style,state.origins,state.history);continue}
   if(t.type==='control-word'){const w=t.word!,p=t.parameter
    if(destinationWords.has(w)){state.destination=w;state.skip=true;destinations.push({name:w,sourceStart:t.start,sourceEnd:t.end,ignorable:star});star=false;continue}
    if(star){state.destination=w;state.skip=true;destinations.push({name:w,sourceStart:t.start,sourceEnd:t.end,ignorable:true});star=false;continue}
    if(w==='uc'&&p!==null){state.uc=Math.max(0,p);continue}
    if(state.skip)continue
    if(w==='b'){state.style.bold=p!==0;origin(state,'bold',state.style.bold,t)}else if(w==='i'){state.style.italic=p!==0;origin(state,'italic',state.style.italic,t)}else if(w==='ul'){state.style.underline=p!==0;origin(state,'underline',state.style.underline,t)}else if(w==='ulnone'){state.style.underline=false;origin(state,'underline',false,t)}
    else if(w==='f'&&p!==null){state.style.font=p;origin(state,'font',p,t)}else if(w==='fs'&&p!==null){state.style.fontSizeHalfPoints=p;origin(state,'fontSizeHalfPoints',p,t)}else if(w==='cf'&&p!==null){state.style.foregroundColor=p;origin(state,'foregroundColor',p,t)}else if((w==='highlight'||w==='cb')&&p!==null){state.style.backgroundColor=p;origin(state,'backgroundColor',p,t)}
    else if(w==='li'&&p!==null){state.style.leftIndentTwips=p;origin(state,'leftIndentTwips',p,t)}else if(w==='ri'&&p!==null){state.style.rightIndentTwips=p;origin(state,'rightIndentTwips',p,t)}else if(w==='fi'&&p!==null){state.style.firstLineIndentTwips=p;origin(state,'firstLineIndentTwips',p,t)}else if(w==='sb'&&p!==null){state.style.spaceBeforeTwips=p;origin(state,'spaceBeforeTwips',p,t)}else if(w==='sa'&&p!==null){state.style.spaceAfterTwips=p;origin(state,'spaceAfterTwips',p,t)}else if(w==='sl'&&p!==null){state.style.lineSpacingTwips=p;origin(state,'lineSpacingTwips',p,t)}else if(w==='tx'&&p!==null){state.style.tabStopsTwips=[...state.style.tabStopsTwips,p];origin(state,'tabStopsTwips',[...state.style.tabStopsTwips],t)}
    else if(w==='ql'){state.style.alignment='left';origin(state,'alignment','left',t)}else if(w==='qc'){state.style.alignment='center';origin(state,'alignment','center',t)}else if(w==='qr'){state.style.alignment='right';origin(state,'alignment','right',t)}else if(w==='qj'){state.style.alignment='justify';origin(state,'alignment','justify',t)}
    else if(w==='plain'){const paragraph={alignment:state.style.alignment,leftIndentTwips:state.style.leftIndentTwips,rightIndentTwips:state.style.rightIndentTwips,firstLineIndentTwips:state.style.firstLineIndentTwips,spaceBeforeTwips:state.style.spaceBeforeTwips,spaceAfterTwips:state.style.spaceAfterTwips,lineSpacingTwips:state.style.lineSpacingTwips,tabStopsTwips:[...state.style.tabStopsTwips]};state.style={...base(),...paragraph};for(const property of ['bold','italic','underline','font','fontSizeHalfPoints','foregroundColor','backgroundColor'] as RtfStyleProperty[])origin(state,property,state.style[property],t,'reset')}else if(w==='pard'){const defaults=base();for(const property of ['alignment','leftIndentTwips','rightIndentTwips','firstLineIndentTwips','spaceBeforeTwips','spaceAfterTwips','lineSpacingTwips','tabStopsTwips'] as RtfStyleProperty[]){state.style[property]=defaults[property] as never;origin(state,property,state.style[property],t,'reset')}}
    else if(w==='par'||w==='line')emit('\n',[t],state.style,state.origins,state.history);else if(w==='tab')emit('\t',[t],state.style,state.origins,state.history)
    else if(w==='u'&&p!==null)emit(String.fromCharCode((p+65536)%65536),[t],state.style,state.origins,state.history)
    continue
   }
   if(state.skip)continue
   if(t.type==='hex-byte')emit(String.fromCharCode(t.hex!),[t],state.style,state.origins,state.history)
   else if(t.type==='text')emit(t.raw,[t],state.style,state.origins,state.history)
  }
 }
 walk(tree.children,{style:base(),origins:{},history:{},groupStart:0,groupEnd:source.length,skip:false,destination:null,uc:1})
 const paragraphs:RtfParagraph[]=[];let current:RtfModelRun[]=[]
 const flush=()=>{if(!current.length)return;const first=current[0],last=current.at(-1)!;paragraphs.push({index:paragraphs.length,start:first.start,end:last.end,sourceStart:first.sourceStart,sourceEnd:last.sourceEnd,runs:current,alignment:first.style.alignment});current=[]}
 for(const run of runs){current.push(run);if(run.text.includes('\n'))flush()}flush()
 const fontGroup=findDestinationGroup(tree.children,'fonttbl'),colorGroup=findDestinationGroup(tree.children,'colortbl')
 const fonts=fontGroup?parseFonts(source,fontGroup.start,fontGroup.end):[],colors=colorGroup?parseColors(source,colorGroup.start,colorGroup.end):[]
 const referenceFor=(property:RtfStyleProperty,value:RtfComputedStyle[RtfStyleProperty]):RtfReferenceTarget|undefined=>{if(property==='font'&&typeof value==='number'){const x=fonts.find(f=>f.index===value);if(x)return {kind:'font',index:x.index,label:x.name,sourceStart:x.sourceStart,sourceEnd:x.sourceEnd}}if((property==='foregroundColor'||property==='backgroundColor')&&typeof value==='number'){const x=colors.find(c=>c.index===value);if(x)return {kind:'color',index:x.index,label:`RGB(${x.red}, ${x.green}, ${x.blue})`,sourceStart:x.sourceStart,sourceEnd:x.sourceEnd}}}
 for(const run of runs)for(const property of Object.keys(run.history) as RtfStyleProperty[])for(const event of run.history[property]||[]){const ref=referenceFor(property,event.value);if(ref)event.reference=ref}
 return {source,paragraphs,runs,destinations,fonts,colors,diagnostics:tree.diagnostics}
}
function findDestinationGroup(nodes:RtfNode[],name:string):Extract<RtfNode,{type:'group'}>|null{for(const n of nodes)if(n.type==='group'){if(n.children.some(x=>x.type==='token'&&x.token.type==='control-word'&&x.token.word===name))return n;const f=findDestinationGroup(n.children,name);if(f)return f}return null}
function parseFonts(source:string,start:number,end:number):RtfModelFont[]{const s=source.slice(start,end),out:RtfModelFont[]=[];for(const m of s.matchAll(/\{\\f(\d+)[\s\S]*? ([^;{}]+);}/g)){const sourceStart=start+m.index!,sourceEnd=sourceStart+m[0].length;out.push({index:Number(m[1]),name:m[2].trim(),sourceStart,sourceEnd})}return out}
function parseColors(source:string,start:number,end:number):RtfModelColor[]{const s=source.slice(start,end),out:RtfModelColor[]=[];let entryStart=0,index=0;for(let i=0;i<=s.length;i++)if(i===s.length||s[i]===';'){const e=s.slice(entryStart,i),r=e.match(/\\red(\d+)/),g=e.match(/\\green(\d+)/),b=e.match(/\\blue(\d+)/);if(r||g||b)out.push({index,red:Number(r?.[1]||0),green:Number(g?.[1]||0),blue:Number(b?.[1]||0),sourceStart:start+entryStart,sourceEnd:start+i+1});index++;entryStart=i+1}return out}
