import {parseRtfTree,type RtfNode,type RtfDiagnostic} from './rtfParser'
import type {RtfToken} from './rtfLexer'
export type RtfModelFont={index:number;name:string;sourceStart:number;sourceEnd:number}
export type RtfModelColor={index:number;red:number;green:number;blue:number;sourceStart:number;sourceEnd:number}
export type RtfListLevel={level:number;numberFormat:number|null;numberFormatName:string;startAt:number|null;levelText:string|null;sourceStart:number;sourceEnd:number}
export type RtfListDefinition={listId:number;templateId:number|null;levels:RtfListLevel[];sourceStart:number;sourceEnd:number}
export type RtfListOverride={listId:number;ls:number;sourceStart:number;sourceEnd:number}
export type RtfListResolution={ls:number;level:number;override:RtfListOverride;list:RtfListDefinition;levelDefinition:RtfListLevel|null}
export type RtfNamedStyle={kind:'paragraph'|'character';index:number;name:string;basedOn:number|null;properties:Partial<RtfComputedStyle>;sourceStart:number;sourceEnd:number}
export type RtfStyleResolution={kind:'paragraph'|'character';index:number;chain:RtfNamedStyle[];missingParent:number|null;cycle:boolean}
export type RtfStyleProperty=keyof RtfComputedStyle
export type RtfProvenanceKind='applied'|'reset'|'override'|'restored'
export type RtfPropertyOrigin={property:RtfStyleProperty;value:RtfComputedStyle[RtfStyleProperty];control:string;sourceStart:number;sourceEnd:number;kind:'applied'|'reset'}
export type RtfReferenceTarget={kind:'font'|'color'|'list-override'|'list-definition'|'list-level';index:number;label:string;sourceStart:number;sourceEnd:number}
export type RtfProvenanceEvent={property:RtfStyleProperty;value:RtfComputedStyle[RtfStyleProperty];previousValue:RtfComputedStyle[RtfStyleProperty];control:string;sourceStart:number;sourceEnd:number;kind:RtfProvenanceKind;groupStart:number;groupEnd:number|null;reference?:RtfReferenceTarget}
export type RtfComputedStyle={bold:boolean;italic:boolean;underline:boolean;font:number|null;fontSizeHalfPoints:number|null;foregroundColor:number|null;backgroundColor:number|null;alignment:'left'|'center'|'right'|'justify';leftIndentTwips:number;rightIndentTwips:number;firstLineIndentTwips:number;spaceBeforeTwips:number;spaceAfterTwips:number;lineSpacingTwips:number|null;tabStopsTwips:number[];listOverride:number|null;listLevel:number|null;paragraphStyle:number|null;characterStyle:number|null}
export type RtfCascadeSource={kind:'default'|'paragraph-style'|'character-style'|'direct';label:string;sourceStart:number|null;sourceEnd:number|null}
export type RtfModelRun={computedStyle?:RtfComputedStyle;cascade?:Partial<Record<RtfStyleProperty,RtfCascadeSource>>;listResolution?:RtfListResolution;paragraphStyleResolution?:RtfStyleResolution;characterStyleResolution?:RtfStyleResolution;text:string;start:number;end:number;sourceStart:number;sourceEnd:number;style:RtfComputedStyle;origins:Partial<Record<RtfStyleProperty,RtfPropertyOrigin>>;history:Partial<Record<RtfStyleProperty,RtfProvenanceEvent[]>>;sourceTokens:RtfToken[]}
export type RtfParagraph={index:number;start:number;end:number;sourceStart:number;sourceEnd:number;runs:RtfModelRun[];alignment:RtfComputedStyle['alignment']}
export type RtfDestination={name:string;sourceStart:number;sourceEnd:number;ignorable:boolean}
export type RtfModel={source:string;paragraphs:RtfParagraph[];runs:RtfModelRun[];destinations:RtfDestination[];fonts:RtfModelFont[];colors:RtfModelColor[];lists:RtfListDefinition[];listOverrides:RtfListOverride[];styles:RtfNamedStyle[];diagnostics:RtfDiagnostic[]}
type State={style:RtfComputedStyle;origins:Partial<Record<RtfStyleProperty,RtfPropertyOrigin>>;history:Partial<Record<RtfStyleProperty,RtfProvenanceEvent[]>>;groupStart:number;groupEnd:number|null;skip:boolean;destination:string|null;uc:number}
const base=():RtfComputedStyle=>({bold:false,italic:false,underline:false,font:null,fontSizeHalfPoints:null,foregroundColor:null,backgroundColor:null,alignment:'left',leftIndentTwips:0,rightIndentTwips:0,firstLineIndentTwips:0,spaceBeforeTwips:0,spaceAfterTwips:0,lineSpacingTwips:null,tabStopsTwips:[],listOverride:null,listLevel:null,paragraphStyle:null,characterStyle:null})
const destinationWords=new Set(['fonttbl','colortbl','stylesheet','info','pict','object','header','footer','headerl','headerr','footerl','footerr','listtable','listoverridetable','generator'])
const cloneStyle=(s:RtfComputedStyle):RtfComputedStyle=>({...s,tabStopsTwips:[...s.tabStopsTwips]})
const same=(a:RtfComputedStyle,b:RtfComputedStyle)=>JSON.stringify(a)===JSON.stringify(b)
const sameOrigins=(a:State['origins'],b:State['origins'])=>JSON.stringify(a)===JSON.stringify(b)
const origin=(state:State,property:RtfStyleProperty,value:RtfComputedStyle[RtfStyleProperty],t:RtfToken,kind:RtfPropertyOrigin['kind']='applied')=>{const previous=state.origins[property],previousValue=(previous?.value??base()[property]) as RtfComputedStyle[RtfStyleProperty];const eventKind:RtfProvenanceKind=kind==='reset'?'reset':previous?'override':'applied';state.origins[property]={property,value,control:t.raw.trim(),sourceStart:t.start,sourceEnd:t.end,kind};state.history[property]=[...(state.history[property]||[]),{property,value,previousValue,control:t.raw.trim(),sourceStart:t.start,sourceEnd:t.end,kind:eventKind,groupStart:state.groupStart,groupEnd:state.groupEnd}]}
export function buildRtfModel(source:string):RtfModel{
 const tree=parseRtfTree(source),runs:RtfModelRun[]=[],destinations:RtfDestination[]=[];let textPos=0
 const emit=(text:string,tokens:RtfToken[],style:RtfComputedStyle,origins:State['origins'],history:State['history'])=>{if(!text)return;const ss=tokens[0]?.start??0,se=tokens.at(-1)?.end??ss,last=runs.at(-1);if(last&&same(last.style,style)&&sameOrigins(last.origins,origins)&&last.end===textPos&&last.sourceEnd===ss){last.text+=text;last.end+=text.length;last.sourceEnd=se;last.sourceTokens.push(...tokens)}else runs.push({text,start:textPos,end:textPos+text.length,sourceStart:ss,sourceEnd:se,style:cloneStyle(style),origins:{...origins},history:Object.fromEntries(Object.entries(history).map(([k,v])=>[k,[...(v||[])]])),sourceTokens:[...tokens]});textPos+=text.length}
 const walk=(nodes:RtfNode[],incoming:State)=>{const state:State={style:cloneStyle(incoming.style),origins:{...incoming.origins},history:Object.fromEntries(Object.entries(incoming.history).map(([k,v])=>[k,[...(v||[])]])),groupStart:incoming.groupStart,groupEnd:incoming.groupEnd,skip:incoming.skip,destination:incoming.destination,uc:incoming.uc};let star=false
  for(const node of nodes){
   if(node.type==='group'){const before=destinations.length;const child:State={...state,style:cloneStyle(state.style),origins:{...state.origins},history:Object.fromEntries(Object.entries(state.history).map(([k,v])=>[k,[...(v||[])]])),groupStart:node.start,groupEnd:node.end};const completed=walk(node.children,child);if(!node.unclosed&&node.close)for(const property of Object.keys(state.style) as RtfStyleProperty[]){if(completed.style[property]!==state.style[property])state.history[property]=[...(state.history[property]||[]),{property,value:state.style[property],previousValue:completed.style[property],control:node.close.raw,sourceStart:node.close.start,sourceEnd:node.close.end,kind:'restored',groupStart:node.start,groupEnd:node.end}]}for(let di=before;di<destinations.length;di++)if(destinations[di].sourceEnd===destinations[di].sourceStart||destinations[di].sourceEnd===node.children[0]?.end)destinations[di].sourceEnd=node.end;continue}
   const t=node.token
   if(t.type==='control-symbol'){if(t.symbol==='*'){star=true;continue}if(!state.skip&&['\\','{','}'].includes(t.symbol||''))emit(t.symbol!,[t],state.style,state.origins,state.history);else if(!state.skip&&t.symbol==='~')emit('\u00a0',[t],state.style,state.origins,state.history);continue}
   if(t.type==='control-word'){const w=t.word!,p=t.parameter
    if(destinationWords.has(w)){state.destination=w;state.skip=true;destinations.push({name:w,sourceStart:t.start,sourceEnd:t.end,ignorable:star});star=false;continue}
    if(star){state.destination=w;state.skip=true;destinations.push({name:w,sourceStart:t.start,sourceEnd:t.end,ignorable:true});star=false;continue}
    if(w==='uc'&&p!=null){state.uc=Math.max(0,p);continue}
    if(state.skip)continue
    if(w==='b'){state.style.bold=p!==0;origin(state,'bold',state.style.bold,t)}else if(w==='i'){state.style.italic=p!==0;origin(state,'italic',state.style.italic,t)}else if(w==='ul'){state.style.underline=p!==0;origin(state,'underline',state.style.underline,t)}else if(w==='ulnone'){state.style.underline=false;origin(state,'underline',false,t)}
    else if(w==='f'&&p!=null){state.style.font=p;origin(state,'font',p,t)}else if(w==='fs'&&p!=null){state.style.fontSizeHalfPoints=p;origin(state,'fontSizeHalfPoints',p,t)}else if(w==='cf'&&p!=null){state.style.foregroundColor=p;origin(state,'foregroundColor',p,t)}else if((w==='highlight'||w==='cb')&&p!=null){state.style.backgroundColor=p;origin(state,'backgroundColor',p,t)}
    else if(w==='li'&&p!=null){state.style.leftIndentTwips=p;origin(state,'leftIndentTwips',p,t)}else if(w==='ri'&&p!=null){state.style.rightIndentTwips=p;origin(state,'rightIndentTwips',p,t)}else if(w==='fi'&&p!=null){state.style.firstLineIndentTwips=p;origin(state,'firstLineIndentTwips',p,t)}else if(w==='sb'&&p!=null){state.style.spaceBeforeTwips=p;origin(state,'spaceBeforeTwips',p,t)}else if(w==='sa'&&p!=null){state.style.spaceAfterTwips=p;origin(state,'spaceAfterTwips',p,t)}else if(w==='sl'&&p!=null){state.style.lineSpacingTwips=p;origin(state,'lineSpacingTwips',p,t)}else if(w==='tx'&&p!=null){state.style.tabStopsTwips=[...state.style.tabStopsTwips,p];origin(state,'tabStopsTwips',[...state.style.tabStopsTwips],t)}else if(w==='ls'&&p!=null){state.style.listOverride=p;origin(state,'listOverride',p,t)}else if(w==='ilvl'&&p!=null){state.style.listLevel=p;origin(state,'listLevel',p,t)}else if(w==='s'&&p!=null){state.style.paragraphStyle=p;origin(state,'paragraphStyle',p,t)}else if(w==='cs'&&p!=null){state.style.characterStyle=p;origin(state,'characterStyle',p,t)}
    else if(w==='ql'){state.style.alignment='left';origin(state,'alignment','left',t)}else if(w==='qc'){state.style.alignment='center';origin(state,'alignment','center',t)}else if(w==='qr'){state.style.alignment='right';origin(state,'alignment','right',t)}else if(w==='qj'){state.style.alignment='justify';origin(state,'alignment','justify',t)}
    else if(w==='plain'){const paragraph={alignment:state.style.alignment,leftIndentTwips:state.style.leftIndentTwips,rightIndentTwips:state.style.rightIndentTwips,firstLineIndentTwips:state.style.firstLineIndentTwips,spaceBeforeTwips:state.style.spaceBeforeTwips,spaceAfterTwips:state.style.spaceAfterTwips,lineSpacingTwips:state.style.lineSpacingTwips,tabStopsTwips:[...state.style.tabStopsTwips],listOverride:state.style.listOverride,listLevel:state.style.listLevel,paragraphStyle:state.style.paragraphStyle};state.style={...base(),...paragraph};for(const property of ['bold','italic','underline','font','fontSizeHalfPoints','foregroundColor','backgroundColor'] as RtfStyleProperty[])origin(state,property,state.style[property],t,'reset')}else if(w==='pard'){const defaults=base();for(const property of ['alignment','leftIndentTwips','rightIndentTwips','firstLineIndentTwips','spaceBeforeTwips','spaceAfterTwips','lineSpacingTwips','tabStopsTwips','listOverride','listLevel','paragraphStyle'] as RtfStyleProperty[]){state.style[property]=defaults[property] as never;origin(state,property,state.style[property],t,'reset')}}
    else if(w==='par'||w==='line')emit('\n',[t],state.style,state.origins,state.history);else if(w==='tab')emit('\t',[t],state.style,state.origins,state.history)
    else if(w==='u'&&p!=null)emit(String.fromCharCode((p+65536)%65536),[t],state.style,state.origins,state.history)
    continue
   }
   if(state.skip)continue
   if(t.type==='hex-byte')emit(String.fromCharCode(t.hex!),[t],state.style,state.origins,state.history)
   else if(t.type==='text')emit(t.raw,[t],state.style,state.origins,state.history)
  }
  return state
 }
 walk(tree.children,{style:base(),origins:{},history:{},groupStart:0,groupEnd:source.length,skip:false,destination:null,uc:1})
 const paragraphs:RtfParagraph[]=[];let current:RtfModelRun[]=[]
 const flush=()=>{if(!current.length)return;const first=current[0],last=current.at(-1)!;paragraphs.push({index:paragraphs.length,start:first.start,end:last.end,sourceStart:first.sourceStart,sourceEnd:last.sourceEnd,runs:current,alignment:first.style.alignment});current=[]}
 for(const run of runs){current.push(run);if(run.text.includes('\n'))flush()}flush()
 const fontGroup=findDestinationGroup(tree.children,'fonttbl'),colorGroup=findDestinationGroup(tree.children,'colortbl'),listGroup=findDestinationGroup(tree.children,'listtable'),overrideGroup=findDestinationGroup(tree.children,'listoverridetable'),styleGroup=findDestinationGroup(tree.children,'stylesheet')
 const fonts=fontGroup?parseFonts(fontGroup):[],colors=colorGroup?parseColors(colorGroup):[],lists=listGroup?parseLists(listGroup):[],listOverrides=overrideGroup?parseListOverrides(overrideGroup):[],styles=styleGroup?parseStyles(styleGroup):[]
 const referenceFor=(property:RtfStyleProperty,value:RtfComputedStyle[RtfStyleProperty]):RtfReferenceTarget|undefined=>{if(property==='font'&&typeof value==='number'){const x=fonts.find(f=>f.index===value);if(x)return {kind:'font',index:x.index,label:x.name,sourceStart:x.sourceStart,sourceEnd:x.sourceEnd}}if((property==='foregroundColor'||property==='backgroundColor')&&typeof value==='number'){const x=colors.find(c=>c.index===value);if(x)return {kind:'color',index:x.index,label:`RGB(${x.red}, ${x.green}, ${x.blue})`,sourceStart:x.sourceStart,sourceEnd:x.sourceEnd}}}
 for(const run of runs){if(run.style.paragraphStyle!==null)run.paragraphStyleResolution=resolveNamedStyle(styles,'paragraph',run.style.paragraphStyle);if(run.style.characterStyle!==null)run.characterStyleResolution=resolveNamedStyle(styles,'character',run.style.characterStyle);applyStyleCascade(run);if(run.style.listOverride!==null){const override=listOverrides.find(x=>x.ls===run.style.listOverride),list=override&&lists.find(x=>x.listId===override.listId);if(override&&list){const level=run.style.listLevel??0,levelDefinition=list.levels.find(x=>x.level===level)||null;run.listResolution={ls:override.ls,level,override,list,levelDefinition}}}
 for(const property of Object.keys(run.history) as RtfStyleProperty[])for(const event of run.history[property]||[]){const ref=referenceFor(property,event.value);if(ref)event.reference=ref}}
 return {source,paragraphs,runs,destinations,fonts,colors,lists,listOverrides,styles,diagnostics:tree.diagnostics}
}
function findDestinationGroup(nodes:RtfNode[],name:string):Extract<RtfNode,{type:'group'}>|null{for(const n of nodes)if(n.type==='group'){if(n.children.some(x=>x.type==='token'&&x.token.type==='control-word'&&x.token.word===name))return n;const f=findDestinationGroup(n.children,name);if(f)return f}return null}
function parseFonts(fontTable:Extract<RtfNode,{type:'group'}>):RtfModelFont[]{const out:RtfModelFont[]=[];for(const group of fontTable.children){if(group.type!=='group')continue;const tokens=directTokens(group),font=tokens.find(t=>t.type==='control-word'&&t.word==='f'&&t.parameter!=null);if(!font||font.parameter==null)continue;const name=tokens.filter(t=>t.type==='text').map(t=>t.raw).join('').split(';',1)[0].trim();out.push({index:font.parameter,name:name||('font '+font.parameter),sourceStart:group.start,sourceEnd:group.end})}return out}
function parseColors(colorTable:Extract<RtfNode,{type:'group'}>):RtfModelColor[]{const tokens=directTokens(colorTable),out:RtfModelColor[]=[];let index=0,entryStart=colorTable.start,red=0,green=0,blue=0,hasColor=false;for(const token of tokens){if(token.type==='control-word'&&token.parameter!=null){if(token.word==='red'){red=token.parameter;hasColor=true}else if(token.word==='green'){green=token.parameter;hasColor=true}else if(token.word==='blue'){blue=token.parameter;hasColor=true}}if(token.type==='text'){let offset=0;for(const ch of token.raw){offset++;if(ch!==';')continue;if(hasColor)out.push({index,red,green,blue,sourceStart:entryStart,sourceEnd:token.start+offset});index++;entryStart=token.start+offset;red=green=blue=0;hasColor=false}}}return out}

function controlParameter(tokens:RtfToken[],word:string):number|null{const token=tokens.find(t=>t.type==='control-word'&&t.word===word&&t.parameter!=null);return token?.parameter??null}
function groupStartsWith(group:Extract<RtfNode,{type:'group'}>,word:string):boolean{return directTokens(group).some(t=>t.type==='control-word'&&t.word===word)}
function nestedGroups(group:Extract<RtfNode,{type:'group'}>,word:string):Extract<RtfNode,{type:'group'}>[] {const out:Extract<RtfNode,{type:'group'}>[]=[];const visit=(nodes:RtfNode[])=>{for(const node of nodes)if(node.type==='group'){if(groupStartsWith(node,word))out.push(node);else visit(node.children)}};visit(group.children);return out}
function parseLevelText(group:Extract<RtfNode,{type:'group'}>):string|null{const levelText=nestedGroups(group,'leveltext')[0];if(!levelText)return null;const value=directTokens(levelText).filter(t=>t.type==='text'||t.type==='hex-byte'||t.type==='control-symbol').map(t=>t.raw).join('');const beforeSemicolon=value.split(';',1)[0].trim();return beforeSemicolon||null}
function parseLists(listTable:Extract<RtfNode,{type:'group'}>):RtfListDefinition[]{const out:RtfListDefinition[]=[];for(const list of nestedGroups(listTable,'list')){const tokens=directTokens(list),listId=controlParameter(tokens,'listid');if(listId===null)continue;const templateId=controlParameter(tokens,'listtemplateid'),levels:RtfListLevel[]=[];for(const [level,levelGroup] of nestedGroups(list,'listlevel').entries()){const levelTokens=directTokens(levelGroup),numberFormat=controlParameter(levelTokens,'levelnfc'),startAt=controlParameter(levelTokens,'levelstartat');levels.push({level,numberFormat,numberFormatName:listNumberFormatName(numberFormat),startAt,levelText:parseLevelText(levelGroup),sourceStart:levelGroup.start,sourceEnd:levelGroup.end})}out.push({listId,templateId,levels,sourceStart:list.start,sourceEnd:list.end})}return out}
function parseListOverrides(table:Extract<RtfNode,{type:'group'}>):RtfListOverride[]{const out:RtfListOverride[]=[];for(const group of nestedGroups(table,'listoverride')){const tokens=directTokens(group),listId=controlParameter(tokens,'listid'),ls=controlParameter(tokens,'ls');if(listId===null||ls===null)continue;out.push({listId,ls,sourceStart:group.start,sourceEnd:group.end})}return out}

export function listNumberFormatName(n:number|null):string{const known:Record<number,string>={0:'decimal',1:'uppercase Roman',2:'lowercase Roman',3:'uppercase letter',4:'lowercase letter',5:'ordinal',6:'cardinal text',7:'ordinal text',22:'leading-zero decimal',23:'bullet'};return n===null?'unspecified':known[n]??`RTF numbering format ${n}`}

function directTokens(group:Extract<RtfNode,{type:'group'}>):RtfToken[]{return group.children.filter((n):n is Extract<RtfNode,{type:'token'}>=>n.type==='token').map(n=>n.token)}
function styleProperties(tokens:RtfToken[]):Partial<RtfComputedStyle>{const p:Partial<RtfComputedStyle>={};for(const t of tokens){if(t.type!=='control-word')continue;const w=t.word,param=t.parameter;if(w==='b')p.bold=param!==0;else if(w==='i')p.italic=param!==0;else if(w==='ul')p.underline=param!==0;else if(w==='ulnone')p.underline=false;else if(w==='fs'&&param!=null)p.fontSizeHalfPoints=param;else if(w==='f'&&param!=null)p.font=param;else if(w==='cf'&&param!=null)p.foregroundColor=param;else if(w==='li'&&param!=null)p.leftIndentTwips=param;else if(w==='ri'&&param!=null)p.rightIndentTwips=param;else if(w==='fi'&&param!=null)p.firstLineIndentTwips=param;else if(w==='sb'&&param!=null)p.spaceBeforeTwips=param;else if(w==='sa'&&param!=null)p.spaceAfterTwips=param;else if(w==='qc')p.alignment='center';else if(w==='qr')p.alignment='right';else if(w==='qj')p.alignment='justify';else if(w==='ql')p.alignment='left'}return p}
function parseStyles(stylesheet:Extract<RtfNode,{type:'group'}>):RtfNamedStyle[]{const out:RtfNamedStyle[]=[];for(const node of stylesheet.children){if(node.type!=='group')continue;const tokens=directTokens(node),selector=tokens.find(t=>t.type==='control-word'&&(t.word==='s'||t.word==='cs')&&t.parameter!=null);if(!selector||selector.parameter==null)continue;const based=tokens.find(t=>t.type==='control-word'&&t.word==='sbasedon'&&t.parameter!=null);const nameText=tokens.filter(t=>t.type==='text').map(t=>t.raw).join('');const name=(nameText.split(';',1)[0].trim()||('style '+selector.parameter));out.push({kind:selector.word==='cs'?'character':'paragraph',index:selector.parameter,name,basedOn:based?.parameter??null,properties:styleProperties(tokens),sourceStart:node.start,sourceEnd:node.end})}return out}
function resolveNamedStyle(styles:RtfNamedStyle[],kind:RtfNamedStyle['kind'],index:number):RtfStyleResolution{const chain:RtfNamedStyle[]=[],seen=new Set<number>();let current:number|null=index,missingParent:number|null=null,cycle=false;while(current!==null){if(seen.has(current)){cycle=true;break}seen.add(current);const style=styles.find(s=>s.kind===kind&&s.index===current);if(!style){missingParent=current;break}chain.unshift(style);current=style.basedOn}return {kind,index,chain,missingParent,cycle}}

function applyStyleCascade(run:RtfModelRun){const computed=base(),cascade:Partial<Record<RtfStyleProperty,RtfCascadeSource>>={};const apply=(properties:Partial<RtfComputedStyle>,kind:RtfCascadeSource['kind'],label:string,start:number|null,end:number|null)=>{for(const property of Object.keys(properties) as RtfStyleProperty[]){const value=properties[property];if(value!==undefined){computed[property]=value as never;cascade[property]={kind,label,sourceStart:start,sourceEnd:end}}}};for(const style of run.paragraphStyleResolution?.chain||[])apply(style.properties,'paragraph-style',style.name,style.sourceStart,style.sourceEnd);for(const style of run.characterStyleResolution?.chain||[])apply(style.properties,'character-style',style.name,style.sourceStart,style.sourceEnd);for(const property of Object.keys(run.origins) as RtfStyleProperty[]){const o=run.origins[property];if(o&&property!=='paragraphStyle'&&property!=='characterStyle')apply({[property]:run.style[property]} as Partial<RtfComputedStyle>,'direct',o.control,o.sourceStart,o.sourceEnd)}computed.paragraphStyle=run.style.paragraphStyle;computed.characterStyle=run.style.characterStyle;computed.listOverride=run.style.listOverride;computed.listLevel=run.style.listLevel;computed.tabStopsTwips=[...computed.tabStopsTwips];run.computedStyle=computed;run.cascade=cascade}
